### PR TITLE
Add the glide storage to .gitignore

### PR DESCRIPTION
**Pull request by jonassiewertsen**

### CODE REVIEW

**Comment by jonassiewertsen** [comment]
Should we add `/storage/statamic` as well?

**Comment by jasonvarga** [comment]
We should probably just add the whole storage/statamic directory. There's nothing in there that you'd really want to track. If you do, you could tweak the default gitignore.

**Comment by jonassiewertsen** [comment]
You're right. 

I did change it.

**Comment by jasonvarga** [comment]
Sorry, not what I meant. The storage/statamic directory, not storage.
Anyway, fixed in 3faa77d7702cdffe24ee83757085dc65fb65d6bf.

**Comment by jonassiewertsen** [comment]
The original problem has not been solved. 

The glide directory is still by default in version control. 
You have written, that the glide directory has been moved inside the statamic folder:
https://github.com/statamic/statamic/pull/8

That's not the case with beta 28.

**Comment by jasonvarga** [comment]
Beta 28 moved the glide directory inside storage/statamic
49a8463af1e3fdb7ce7d3196d05249f7262a1a21

**Comment by jonassiewertsen** [comment]
My fault. 

The project I have been testing with, was one beta behind (beta 27)

**Pull request closed without merging**
