### PR TITLE
Laravel 9.x Shift

### PR DESCRIPTION
**Pull request by jackmcdade**
This pull request includes the changes for upgrading to Laravel 9.x. Feel free to commit any additional changes to the `shift-55082` branch.

**Before merging**, you need to:

- Checkout the `shift-55082` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by jackmcdade** [comment]
:information_source: Laravel 9 moved the `resources/lang` folder to the top level of the project. While Shift moved and replaced references to this folder, you may have additional references to this folder which need to be updated.

**Comment by jackmcdade** [comment]
:warning: Laravel 9 transitioned from SwiftMailer to Symfony Mailer. While this transition should be relatively seamless and Shift automates any tedious changes, there are some changes which are not reliably automated.

**Dependencies**
Some mail providers may require an additional dependency. For example, if you are using Mailgun, then you will need to install the `symfony/mailgun-mailer` package:

```sh
composer require symfony/mailgun-mailer
```

**Updated Return Types**
The `send`, `html`, `text`, and `plain` methods no longer return the number of recipients that received the message.

**Failed Recipients**
It is no longer possible to retrieve a list of failed recipients after sending a message. Instead, a `Symfony\Component\Mailer\Exception\TransportExceptionInterface` exception will be thrown if a message fails to send. Instead of relying on retrieving invalid email addresses after sending a message, it is recommend that you validate email addresses before sending the message instead.

For more details on what has changed you may review the [Symfony Mailer](https://laravel.com/docs/9.x/upgrade#symfony-mailer) section of the _Upgrade Guide_.

**Comment by jackmcdade** [comment]
:x: Shift could not upgrade the following files since they differed from the default Laravel version. You will need to compare these files against the [default Laravel 9 versions](https://github.com/laravel-shift/laravel-9.x/) and merge any changes:

- [ ] lang/en/auth.php
- [ ] lang/en/validation.php

**Comment by jackmcdade** [comment]
:warning: The `FILESYSTEM_DRIVER` environment variable was renamed to `FILESYSTEM_DISK` in Laravel 9. Shift attempted to [automate this change](https://github.com/statamic/statamic/pull/43/commits/14b593728c2b3770d8bf8fd7e1757e6c7a007bd3?w=1), but you should review any additional environment configuration and rename this variable.

**Comment by jackmcdade** [comment]
:information_source: The `FILESYSTEM_CLOUD` environment variable was removed in a later release of Laravel 8. While you may still use the `cloud` disk, you are encouraged to [configure your own disks](https://laravel.com/docs/9.x/filesystem#configuration).

Shift found references to the `FILESYSTEM_CLOUD` variable in the following files:

- [ ] ./config/filesystems.php

**Comment by jackmcdade** [comment]
:warning: The `token` driver for API authentication is no longer available. This driver was not very robust and was removed from the documentation. Laravel now recommends using [Sanctum](https://laravel.com/docs/9.x/sanctum).

If you were using the `token` driver, you may re-add it within your `auth.php` configuration file, then migrate to _Sanctum_ at your convenience.

**Comment by jackmcdade** [comment]
:information_source: Shift [updated your dependencies](https://github.com/statamic/statamic/pull/43/commits/a62e9e291f2b7b897d4db7a705c17687b0ec7cfa?w=1) for Laravel 9. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 9.

Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any additional package incompatibilities.

**Comment by jackmcdade** [comment]
:information_source: Laravel 9 adopted [anonymous migrations](https://laravel-news.com/laravel-anonymous-migrations). Shift [automated this change](https://github.com/statamic/statamic/pull/43/commits/d7e8ef36752dfc91648abbae11e364cc8befd3cf?w=1) to align with modern Laravel conventions and avoid naming migrations.

**Comment by jackmcdade** [comment]
:information_source: The HTTP client has been updated to have a default timeout of 30 seconds. Previously there was no default. The underlying request would wait indefinitely. Now an exception is thrown after 30 seconds.

If you find your requests need longer, you may prefix your request to specify a timeout:

```php
Http::timeout(60)->get("https://laravelshift.com");
```

**Comment by jackmcdade** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel and PHP applications.

**Comment by jesseleite** [comment]
Retriggering since we committed an 8.x shift to the 3.3 base branch.

**Pull request closed without merging**
