### PR TITLE
Update to Tailwind 2.0 and match original colors

### PR DESCRIPTION
**Pull request by robdekort**
* Upgraded to Tailwind 2 compatibility build.
* Match the original chosen colors for the `layout` and `home` templates a little better.

### CODE REVIEW

**Comment by robdekort** [comment]
In response to: https://statamic.com/forum/5092-tailwind-2-0

**Comment by robdekort** [comment]
Just upgraded this PR to Laravel Mix 6 as well.

**Comment by HRR1337** [comment]
When I use this, can I still update Statamic?

**Comment by robdekort** [comment]
Yeah you should be. This is basically the default starter kit and independent from the actual CMS.

**Comment by jackmcdade** [comment]
Just FYI, this will likely be merged in conjunction with 3.1. :)

**Comment by HRR1337** [comment]
> Just FYI, this will likely be merged in conjunction with 3.1. :)

Perfect! Then I'll wait.

**Comment by HRR1337** [comment]
I have tested it locally, though there ins an issue. Tailwind is not official compatable with PostCSS 8. see: https://tailwindcss.com/docs/installation

**Comment by robdekort** [comment]
Hmm. It should be with Mix 6 and not using the compat. build. I've it running here on multiple projects.

**Comment by HRR1337** [comment]
> Hmm. It should be with Mix 6 and not using the compat. build. I've it running here on multiple projects.

Can you test with: https://tailwindcss.com/docs/gradient-color-stops << gradients. Had issues with that.

**Comment by robdekort** [comment]
Sure, what exactly do you want me to test. Extending the color stops? Do you have a tw.config snippet?

**Comment by HRR1337** [comment]
Just an button with css. For me this gives me an white background button when I upgrade.

`<button type="button" class="w-full px-6 py-3 mt-6 text-lg font-semibold leading-5 text-white transition duration-150 ease-in-out border border-transparent rounded-md shadow-md sm:w-auto bg-gradient-to-r from-orange-500 to-pink-500 hover:to-pink-600 focus:outline-none focus:shadow-outline-gray">Button</button>`

**Comment by robdekort** [comment]
No issue here when I change them to the colors I actually use on this project, are you sure you have those colors enabled in your config?

**Comment by robdekort** [comment]
Just pulled it down again and all combines fine. I think you might be running into the fact that default color palette changed in Tailwind 2 so colors you expect there to be aren't there anymore. Like orange. Pink and Red are still there. See this for some more info: https://tailwindcss.com/docs/upgrading-to-v2#configure-your-color-palette-explicitly

**Comment by robdekort** [comment]
So if you update your snippet to this you will probably see a (hideous) gradient. Hope it helps!
```
<button type="button" class="w-full px-6 py-3 mt-6 text-lg font-semibold leading-5 text-white transition duration-150 ease-in-out border border-transparent rounded-md shadow-md sm:w-auto bg-gradient-to-r from-blue-500 to-pink-500 hover:to-pink-600 focus:outline-none focus:shadow-outline-gray">Button</button>
```

**Comment by jasonvarga** [comment]
I haven't had a chance to test this out yet, but if you're having issues, maybe you can compare to how Laravel upgraded to mix 6 here https://github.com/laravel/laravel/pull/5505

**Comment by HRR1337** [comment]
> Just pulled it down again and all compiles fine here. I think you might be running into the fact that default color palette changed in Tailwind 2 so colors you expect there to be aren't there anymore. Like orange. Pink and Red are still there. See this for some more info: https://tailwindcss.com/docs/upgrading-to-v2#configure-your-color-palette-explicitly

Exactly indeed the issue. Can confirm its working.

**Comment by robdekort** [comment]
Good. Thanks for the feedback on this.

**Comment by jasonvarga** [comment]
Merged to master, and will be in the 3.1 release. Thanks!

**Pull request closed without merging**
